name: Build Iframely Image

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: iframely
  GITHUB_REGISTRY: ghcr.io
  GITHUB_PROJECT: iframely-server

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build and Push the Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.GITHUB_PROJECT }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.GITHUB_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
